name: inline
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bubble: ^1.2.1
  shared_preferences: ^2.0.15
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: logo
      fonts:
        - asset: assets/fonts/logo.otf

    - family: medium
      fonts:
        - asset: assets/fonts/medium.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/semibold.ttf
